# Java Gradle CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-java/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx2048m
      TERM: dumb

    steps:
      - run:
          name: "Setup AWS credentials"
          command: |
              mkdir ~/.aws && printf "[profile eb-cli]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/config
      - run:
          name: "Install pip"
          command: |
              sudo apt update
              sudo apt install -y python-pip python-dev
              pip --version
      - run:
          name: "Install AWS EB CLI"
          command: |
              sudo pip install awsebcli
              eb --version

      # Checkout Git Repository
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: grailsapp-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      # Execute Access
      - run: chmod +x gradlew

      - save_cache:
          paths:
              - ~/.gradle
          key: grailsapp-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      # Run Unit Tests
      - run: ./gradlew test
      - store_artifacts:
          path: build/test-results/test
          destination: tests

      # Download and cache dependencies
      - run: ./gradlew build --refresh-dependencies

      # WAR File
      - run: ./gradlew war
      - store_artifacts:
          path: build/libs
          destination: apps

      # Deploy Application
      - run: eb deploy sambastatistics