version: 2
jobs:
  build:
    environment:
        JVM_OPTS: -Xmx1024m
        TERM: dumb
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout
      - restore_cache:
                key: grailsapp-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run: chmod +x gradlew
      - save_cache:
                paths:
                  - ~/.gradle
                key: grailsapp-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run: ./gradlew --console=plain -Dgeb.env=chromeHeadless check
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results